apiVersion: v1
kind: Pod
metadata:
  name: test-pv-pod
  namespace: mec
spec:
  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: test-pv-claim
  containers:
    - name: test-pv-container
      image: ht-hub.21cn.com/library/nginx:alpine
      imagePullPolicy: Always	
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pv-storage

